fixed initialization problems

diff --git a/gitce b/gitce
--- a/gitce
+++ b/gitce
@@ -39,5 +39,6 @@ if [ -f $COMMAND_SCRIPT ]; then
 	. $LIB/init.sh
 	. $COMMAND_SCRIPT $*
 else
-	panic "Command $COMMAND not found!"
+	echo "Command $COMMAND not found!" >&2
+	exit 1
 fi
